FROM docker.io/library/archlinux:base-devel
ARG GDB_DIR=/opt/gdb/

# Add files
ADD pacman.txt aur.txt /tmp/

# Install pacman packages
RUN pacman --noconfirm -Sy $(sed 's: #.*$::g' /tmp/pacman.txt | tr '\n' ' ')

# Install pwndbg and GEF with extras
# Install pwndbg before GEF extras due to PIP conflicts
RUN mkdir -p $GDB_DIR && \
        cd $GDB_DIR && \
        git clone https://github.com/pwndbg/pwndbg && \
        cd pwndbg && \
        ./setup.sh && \
	cd .. && \
        git clone --branch main https://github.com/hugsy/gef && \
        git clone --branch dev https://github.com/hugsy/gef-extras && \
        pip install -r gef-extras/requirements.txt

# Add user
ARG user=builder
RUN useradd --system --create-home $user && \
	echo "$user ALL=(ALL:ALL) NOPASSWD:ALL" > /etc/sudoers.d/$user
USER $user

# Install paru
RUN git clone https://aur.archlinux.org/paru-bin.git /tmp/paru && \
	cd /tmp/paru && \
	makepkg --noconfirm -sri

# Install AUR packages
RUN paru --noconfirm --removemake --cleanafter -S $(sed 's: #.*$::g' /tmp/aur.txt | tr '\n' ' ')

# Clean
USER root
RUN userdel -r $user && \
	rm -rf /etc/sudoers.d/$user /tmp/*  /root/{,.[!.],..?}*

